# Header
show_search: true
menu:
  home: /
  address-card: /about

homeMenu:
  address-card: /about
#  file-alt: /archives
  linkedin: https://www.linkedin.com/in/ikertxu
  github: http://github.com/orloxx

# Sidebar
sidebar: right
show_count: true
widgets:
  - tags
  - monthly
#  - yearly

# Share on social media
share:
  - twitter
  - facebook
  - reddit

# Social media handlers
social:
  linkedin: https://www.linkedin.com/in/ikertxu
  github: http://github.com/orloxx
