# Main-nav
home: Home
archive: Archives
search: Search

# Socialmedia
linkedin: LinkedIn
github: GitHub
twitter: Twitter

Read more...: Read more...
Share: Share
Monthly: By Month
Yearly: Yearly
Tags: Tags
