# Main-nav
home: Home
file-alt: About me
search: Search

# Socialmedia
linkedin: LinkedIn
github: GitHub
twitter: Twitter

Read more...: Read more...
Share: Share
Monthly: By Month
Yearly: Yearly
Tags: Tags

Next page: Next page
Prev page: Previous page
